    zn "%SYS"

    // Unexpire passwords and set up passwordless mode to simplify dev use.
    do ##class(Security.Users).UnExpireUserPasswords("*")
    zpm "install passwordless"
    zpm "install item"
    zn "USER"
    // Create /_vscode web app to support intersystems-community.testingmanager VS Code extension
    zpm "install vscode-per-namespace-settings"
    // this should be the place for individual application code.
    zpm "install isc-mem-config"
     halt

